#sudo: required
#language: c
language: rust

install:
  - curl -O https://raw.githubusercontent.com/spawngrid/kerl/master/kerl
  - chmod a+x kerl
  - export OUT_DIR=`pwd`
  - echo ${OUT_DIR}
  - ./kerl update releases
  - ./kerl list releases
  - ./kerl list installations
  - ./kerl build 17.5 erlang-17.5
  - ./kerl list builds
  - ./kerl install erlang-17.5 ./otp
  - chmod a+x ./otp/activate 
  - ./otp/activate
  - ./kerl cleanup all
  - ./kerl list installations 
  - export PATH=${PATH}:./otp/bin
  - echo ${PATH}
  - whereis escript
  - whereis erl
  - erl -version

script:
  - escript gen_api.erl
  - cargo build --verbose
  - cargo build --verbose --no-default-features
  - cargo test --verbose
  - cargo test --verbose --no-default-features
  - rustdoc --test README.md -L target
  - cargo doc --no-deps

branches:
  only:
    - fixtravis
